apiVersion: apps/v1
kind: Deployment
metadata:
  name: franciscomj0398
spec:
  replicas: 1
  selector:
    matchLabels:
      app: franciscomj0398
  template:
    metadata:
      labels:
        app: franciscomj0398
    spec:
      containers:
      - image: okteto.dev/franciscomj0398:latest
        name: franciscomj0398
        envFrom:
        - configMapRef:
            name: franciscomj0398-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: franciscomj0398
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "franciscomj0398"
    port: 8080
  selector:
    app: franciscomj0398
